project:
  type: website

website:
  title: "MDS Knowledge Map"
  navbar:
    left:
      - index.qmd
    right: 
      - icon: github
        href: https://github.com/shreyakakachery/mds-knowledge-map
        aria-label: GitHub